Reboot only after timeout without interruption by Ctrl+C

diff --git a/bin/lalalabos-postinstall b/bin/lalalabos-postinstall
--- a/bin/lalalabos-postinstall
+++ b/bin/lalalabos-postinstall
@@ -82,4 +82,13 @@ for f in /opt/lalalab-scripts/bin/install-*; do
     bash "$f" || break # if needed 
 done
 
-reboot
+# Reboot after some timeout
+TIMEOUT=30
+for (( i=$TIMEOUT; i>=0; i-- ))
+do
+    echo -ne "Rebooting in "$i"s. Press Ctrl+C to abort.\r";
+    sleep 1;
+done
+if [ $? -ne 0 ]; then
+    reboot
+fi
